### PR TITLE
Add step_filter

### PR DESCRIPTION
**Pull request by AlexReimann**
Adds a `StepFilter`, which simply results in a layer which has the highest differences to the neighboring cells.

Mostly copy & paste from the `MinFilter`.

Has settings for the neighbor cell radius and if negative differences should be included

### CODE REVIEW

**Comment by mktk1117** [comment]
Thanks for your PR!
What was the issue you tried to fix with this filter?

**Comment by mktk1117** [comment]
Selection_119
With your original implementation, the border of the invalid cells have large step value.
By checking the validity of the neighboring cells, the map becomes like this.
Selection_118
Which one do you intend?

**Comment by AlexReimann** [comment]
> Which one do you intend?

The second one, but I wonder why I didn't see this before.

We definitely have "NAN" cells from clearing, which should currently cause an issue then.
Can you supply a patch?

**Comment by mktk1117** [comment]
Okay, please have a look at this branch, which is a modified one from your PR.
https://github.com/leggedrobotics/elevation_mapping_cupy/tree/step_filter

**Comment by AlexReimann** [comment]
Closing we are running now with heavy modifications, so not putting effort into getting this back into upstream anymore.

**Pull request closed without merging**
