### PR TITLE
Feature/move grid map rsl

### PR DESCRIPTION
**Pull request by rubengrandia**
moves grid_map_filters_rsl from the anymal_rsl_locomotion repo.
git history is preserved

### CODE REVIEW

**Comment by lorenwel** [comment]
I don't understand this PR. Why do you want to move this here?
These are just generic grid map filters, all implemented in Eigen on CPU. In my eyes this doesn't really match the whole "elevation mapping on GPU" which is the point of this package.

**Comment by rubengrandia** [comment]
It is necessary because the plane segmentation, which will be added in a second PR, depends on several of these in the middle of the pipeline. They can therefore not be executed on the GPU side before receiving the map.

**Comment by lorenwel** [comment]
Takahiro explained to me that your plane segmentation is apparently very difficult to do on GPU. And if I understand your comment correctly, you need to do these filtering operation **during** plane segmentation, such that you couldn't pre-compute them as a layer on GPU. 

If that's the case, then your plane segmentation is quite separate from the elevation mapping package, and in fact, there's no reason why you couldn't run it on the output of the CPU elevation_mapping package. 

I don't know how exactly you were planning to structure the plane segmentation. But it seems to me, the cleanest way of structuring it would be to have the plane segmentation as a separate node or nodelet, which subscribes to the output of elevation_mapping_cupy. There's no huge need to jam it into the CPP part of elevation_mapping_cupy, only to avoid publishing and subscribing once. ROS2 will/would solve this anyway.

In that case, I would advocate for creating a separate repo for plane_segmentation. It will give your algorithm more visibility and people do not have to clone elevation_mapping_cupy, if they want to use your algorithm on CPU elevation_mapping, for example. We could then include that repo as a submodule here and add it to the launch file, if you and @mktk1117 want to have plane segmentation as part of this repo by default.

Structurally, this makes more sense to me than duplicating many filters in Cpp on CPU.

**Comment by rubengrandia** [comment]
The long term vision is to slowly migrate things to the GPU. For that it is more convenient to have things in one repo.

> There's no huge need to jam it into the CPP part of elevation_mapping_cupy, only to avoid publishing and subscribing once. ROS2 will/would solve this anyway.

I agree, we will not do that. Everything added will be in separate packages, so you don't even need to build it if you don't use it.

**Comment by lorenwel** [comment]
Understood. 
In that case may I suggest putting both packages into a joint folder, to avoid cluttering the main repo page:
```
|__ elevation_map_msgs
|__ elevation_mapping_cupy
|__ plane_segmentation  
        |__ plane_segmentation
        |__ grid_map_filters_rsl
```

**Pull request merged**
